name: Capture Dashboard Screenshots

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual trigger

jobs:
  capture-screenshots:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install selenium pillow webdriver_manager
    
    - name: Start Dashboard
      run: |
        python scripts/api_server.py &
        sleep 10  # Wait for dashboard to start
    
    - name: Capture Screenshots
      run: |
        python scripts/capture_screenshots.py
    
    - name: Commit and Push Screenshots
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/screenshots/*.png
        git commit -m "Update dashboard screenshots [skip ci]" || echo "No changes to commit"
        git push
